repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.85.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
      args: ['--args=--hide modules,resources,providers,data-sources']
