repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.71.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tfsec
    - id: terraform_docs
      args: ['--args=--hide modules,resources']
