name: CI
on: [push, pull_request]

jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: [ 0.12.29, 0.13.5 ]
        tflint-version: [ 0.20.2 ]
    steps:
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip terraform_${TF_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          rm terraform_${TF_VERSION}_linux_amd64.zip
        env:
          TF_VERSION: ${{ matrix.terraform-version }}

      - name: Install tflint
        run: |
          wget https://github.com/wata727/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
          rm tflint_linux_amd64.zip
        env:
          TFLINT_VERSION: ${{ matrix.tflint-version }}

      - uses: actions/checkout@v1
      - run: terraform fmt -check
      - run: tflint .

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install --pre flake8==3.8.4 black==20.8b1

      - uses: actions/checkout@v1
      - run: flake8
      - run: black --check .

  test-python:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-1
    strategy:
      matrix:
        lambda:
          - notifier
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install boto3==1.10.45

      - uses: actions/checkout@v1
      - run: python -m tests
        working-directory: lambdas/${{ matrix.lambda }}
